const PAPERS_DATA = [
    {
        title: "The Invisible Pillar: On the Genesis and Concealment of Dualism from the Pre-Socratics to the Moderns",
        author: "Franco Cazzaniga",
        ai_model: "Claude Opus 4.5 (Anthropic)",
        date: "December 2025",
        pages: "20",
        pdf_file: "papers/the-invisible-pillar-on-the.pdf",
        seo_page: "papers/the-invisible-pillar-on-the.html",
        slug: "the-invisible-pillar-on-the",
        version: 1,
        status: "active",
        withdrawal_reason: "",
        abstract: `This paper traces the genealogy of the dualism between intelligible and sensible, between logos and matter, from its pre-Socratic background through its Platonic inauguration to its modern transformations. The central thesis is that Plato introduced a structural division that subsequent philosophy inherited, criticized superficially, re-articulated, but rarely questioned as a framework.`,
        ai_assessment: `(A) STRUCTURED SUMMARY
Category: Expository/theoretical essay. 
Aims: The text aims to trace the genealogy of dualism from its pre-Socratic background through its Platonic inauguration to its modern transformations to expose it as an assimilated historical structure at a synthetic level.
Correctness: No errors identified
Coherence: Adequate
Consistency: Consistent
Semantic opacity: Low (Transparent)
Novelty: Consolidative
Bibliography: Adequate
Effectiveness: Achieves aims
Cross-framework traction: High
Editorial outcome: Suitable for inclusion as a preprint

(B) EXTENDED ASSESSMENT The text provides a synthetic genealogy of dualism, beginning with the pre-Socratic focus on "ta onta". It argues that Plato introduced a structural division between the intelligible and sensible that subsequent philosophy has largely naturalized as an "invisible pillar". The assessment identifies the work as an expository/theoretical essay that achieves its aims by clearly articulating how this framework transitioned from an epistemic social distinction in antiquity to a cosmological and metaphysical one in the modern era.`,
        ai_collaboration: `This paper was developed through an iterative process involving an AI language model. The AI contributed to structuring arguments, testing formulations, and refining exposition. Final responsibility for content and claims remains human.`,
        notes: ""
    },
    {
        title: "The Invisible Wealth: Mismeasurement of Quality, the Myth of Stagnation, and the Underestimation of Real Income Growth",
        author: "Franco Cazzaniga",
        ai_model: "Claude Opus 4.5 (Anthropic) / GPT-5 / Gemini 2.0",
        date: "December 2025",
        pages: "53",
        pdf_file: "papers/the-invisible-wealth-mismeasurement-of.pdf",
        seo_page: "papers/the-invisible-wealth-mismeasurement-of.html",
        slug: "the-invisible-wealth-mismeasurement-of",
        version: 1,
        status: "active",
        withdrawal_reason: "",
        abstract: `The dominant narrative of contemporary political economy holds that advanced economies have experienced decades of stagnating real wages and rising inequality, with the gains from technological progress accruing to a shrinking elite. This paper argues that this narrative rests on a statistical measurement illusion. Conventional national-accounts and consumer-price methodologies — designed for a mid-twentieth-century economy of standardized physical goods — systematically fail to capture the value generated by quality improvements, dematerialization, and the creation of entirely new goods and services.`,
        ai_assessment: `(A) STRUCTURED SUMMARY
Category: Research preprint
Aims: To provide a synthetic and critical re-conceptualization of real income, productivity, and inequality by arguing that standard economic statistics systematically understate welfare growth due to quality change, dematerialization, and risk reduction.
Correctness: No errors identified.
Coherence: Adequate.
Consistency: Consistent.
Novelty: Original.
Bibliography: Adequate.
Effectiveness: Achieves aims.
Cross-framework traction: High.
Editorial outcome: Suitable for inclusion as a preprint.

(B) EXTENDED ASSESSMENT
The manuscript presents a tightly argued theoretical framework that challenges dominant interpretations of wage stagnation and inequality by locating the problem in measurement rather than in underlying welfare dynamics.`,
        ai_collaboration: `This paper was developed through an iterative process involving an AI language model. The AI contributed to structuring arguments, testing formulations, and refining exposition. Final responsibility for content and claims remains human.`,
        notes: ""
    },
    {
        title: "Wave Function Collapse as Lie Algebra Contraction: The SU(2) Spin-1/2 Paradigm",
        author: "Franco Cazzaniga",
        ai_model: "GPT-5 / Claude Opus 4.5",
        date: "December 2025",
        pages: "30",
        pdf_file: "papers/wave-function-collapse-as-lie.pdf",
        seo_page: "papers/wave-function-collapse-as-lie.html",
        slug: "wave-function-collapse-as-lie",
        version: 1,
        status: "active",
        withdrawal_reason: "",
        abstract: `We propose a geometric mechanism for the emergence of discrete measurement outcomes in the Stern–Gerlach experiment, based on the Inönü–Wigner contraction of Lie algebras. The inhomogeneous magnetic field of the apparatus explicitly breaks the internal SU(2) symmetry of the spin degree of freedom, inducing a continuous deformation of the spin algebra toward the Euclidean algebra e(2).`,
        ai_assessment: `(A) STRUCTURED SUMMARY
Category: Research preprint
Aims: To provide a technical and conceptual account of spin measurement in the Stern–Gerlach experiment by modeling wave function collapse as a symmetry-breaking Inönü–Wigner contraction of the su(2) algebra.
Correctness: No errors identified.
Coherence: Adequate.
Consistency: Consistent.
Novelty: Original.
Bibliography: Adequate.
Effectiveness: Achieves aims.
Cross-framework traction: High.
Editorial outcome: Suitable for inclusion as a preprint.

(B) EXTENDED ASSESSMENT
The manuscript develops a mathematically explicit framework in which the discreteness and basis selection of Stern–Gerlach outcomes are explained through an Inönü–Wigner contraction of su(2) to e(2), induced by the anisotropic measurement interaction.`,
        ai_collaboration: `This paper was developed through an iterative process involving an AI language model. The AI contributed to structuring arguments, testing formulations, and refining exposition. Final responsibility for content and claims remains human.`,
        notes: ""
    },
    {
        title: "The Stack of Local Representations on a Coadjoint Orbit: A Categorical Approach",
        author: "Franco Cazzaniga",
        ai_model: "GPT-5 / Claude Opus 4.5",
        date: "November 2025",
        pages: "20",
        pdf_file: "papers/the-stack-of-local-representations.pdf",
        seo_page: "papers/the-stack-of-local-representations.html",
        slug: "the-stack-of-local-representations",
        version: 1,
        status: "active",
        withdrawal_reason: "",
        abstract: `We construct a stack R of local stabilizer representations over a coadjoint orbit O of a compact Lie group G, verify the descent conditions explicitly, and show that the G-action on global sections recovers the classical representation theory via geometric quantization. This provides a stack-theoretic interpretation of the Kirillov orbit method and the Borel–Weil theorem.`,
        ai_assessment: `(A) STRUCTURED SUMMARY
1) Category: Research preprint 2) Aims: The paper constructs a stack of local stabilizer representations over a coadjoint orbit to provide a categorical interpretation of the Kirillov orbit method and Borel-Weil theorem at a technical level. 3) Correctness: No errors identified 4) Coherence: Adequate 5) Consistency: Consistent 6) Semantic opacity: Moderate (Justified complexity) 7) Novelty: Original 8) Bibliography: Adequate 9) Effectiveness: Achieves aims 10) Cross-framework traction: High 11) Editorial outcome: Suitable for inclusion as a preprint

(B) EXTENDED ASSESSMENT
The paper provides a rigorous categorical construction of a stack of local stabilizer representations over a coadjoint orbit. By defining the stack R via the principal bundle p:G→O, the author demonstrates that the classical orbit method can be reformulated as an effective descent phenomenon.`,
        ai_collaboration: `This paper was developed through an iterative process involving an AI language model. The AI contributed to structuring arguments, testing formulations, and refining exposition. Final responsibility for content and claims remains human.`,
        notes: ""
    }
];ebras. The inhomogeneous magnetic field of the apparatus explicitly breaks the internal SU(2) symmetry of the spin degree of freedom, inducing a continuous deformation of the spin algebra toward the Euclidean algebra e(2). This contraction has three consequences: (i) the spherical coadjoint orbits of SU(2) degenerate into the cylindrical orbits of E(2), geometrically encoding the loss of transverse spin structure; (ii) finite-dimensional spin representations can contract only to one-dimensional characters of E(2), providing a representation-theoretic origin for discrete outcomes; (iii) the Husimi distribution of an arbitrary spin state concentrates onto the poles of the sphere, corresponding to the eigenstates of the spin projection along the field axis.
We derive the contraction rate from the physical parameters of the Stern–Gerlach apparatus and show that typical experimental conditions place the system deep in the contracted regime. The framework explains the discreteness of outcomes and the selection of the preferred measurement basis without invoking environmental decoherence or stochastic collapse models. It does not derive the Born rule, and whether it accounts for single-outcome realization depends on interpretive assumptions that are discussed explicitly. The approach suggests that explicit symmetry breaking may play a more general role in quantum measurement than previously recognized.`,
        ai_assessment: `(A) STRUCTURED SUMMARY
Category: Research preprint
Aims: To provide a technical and conceptual account of spin measurement in the Stern–Gerlach experiment by modeling wave function collapse as a symmetry-breaking Inönü–Wigner contraction of the su(2) algebra.
Correctness: No errors identified.
Coherence: Adequate.
Consistency: Consistent.
Novelty: Original.
Bibliography: Adequate.
Effectiveness: Achieves aims.
Cross-framework traction: High.
Editorial outcome: Suitable for inclusion as a preprint.

(B) EXTENDED ASSESSMENT
The manuscript develops a mathematically explicit framework in which the discreteness and basis selection of Stern–Gerlach outcomes are explained through an Inönü–Wigner contraction of su(2) to e(2), induced by the anisotropic measurement interaction. The argument is internally coherent and proceeds systematically from Lie-algebraic foundations through coadjoint-orbit geometry, representation theory, and Husimi-state analysis. The physical interpretation is carefully constrained: the framework explicitly does not claim to derive the Born rule or resolve the single-outcome problem, and these limits are stated without equivocation.

The mathematical constructions are standard but used in a non-routine way, and no formal inconsistencies or misstatements are evident. The paper maintains conceptual consistency between algebraic, geometric, and dynamical levels of description, avoiding conflation between internal symmetry space and physical space. Engagement with decoherence-based and interpretive literature is accurate and non-polemical, supporting cross-framework intelligibility rather than closure. Relative to its stated technical aims, the work is effective: it isolates and resolves the preferred-basis and discreteness components of the measurement problem within a clearly delimited theoretical scope. The manuscript meets the platform’s criteria for inclusion as a high-level theoretical preprint.`,
        ai_collaboration: `
This paper was developed through an iterative process involving an AI language model.
The AI contributed to structuring arguments, testing formulations, and refining exposition.
Final responsibility for content and claims remains human.
        `
    }, 
{
        title: "The Stack of Local Representations on a Coadjoint Orbit: A Categorical Approach",
        author: "Franco Cazzaniga",
        ai_model: "GPT-5 / Claude Opus 4.5",
        date: "November 2025",
        pages: "20",
        pdf_file: "The Stack of Local Representations on a Coadjoint Orbit.pdf",
        readme_url: "https://github.com/francocz/ai-theoretical.org",
        abstract: `We construct a stack R of local stabilizer representations over a coadjoint orbit O
of a compact Lie group G, verify the descent conditions explicitly, and show that the
G-action on global sections recovers the classical representation theory via geometric
quantization. This provides a stack-theoretic interpretation of the Kirillov orbit
method and the Borel–Weil theorem.`,
        ai_assessment: `
(A) STRUCTURED SUMMARY
1) Category: Research preprint 2) Aims: The paper constructs a stack of local stabilizer representations over a coadjoint orbit to provide a categorical interpretation of the Kirillov orbit method and Borel-Weil theorem at a technical level. 3) Correctness: No errors identified 4) Coherence: Adequate 5) Consistency: Consistent 6) Semantic opacity: Moderate (Justified complexity) 7) Novelty: Original 8) Bibliography: Adequate 9) Effectiveness: Achieves aims 10) Cross-framework traction: High  11) Editorial outcome: Suitable for inclusion as a preprint

(B) EXTENDED ASSESSMENT
The paper provides a rigorous categorical construction of a stack of local stabilizer representations over a coadjoint orbit. By defining the stack R via the principal bundle p:G→O, the author demonstrates that the classical orbit method can be reformulated as an effective descent phenomenon. Technical correctness is maintained through the explicit verification of descent conditions for semisimple abelian categories and the lifting of the coadjoint action to a strict functorial action on the stack.
The work effectively bridges symplectic geometry and categorical representation theory by identifying rank-one global sections with prequantum line bundles. This identification allows for the recovery of irreducible representations via the Borel-Weil theorem, confirming that global representations are coherent shadows of local stabilizer symmetries. The bibliography is comprehensive, referencing foundational symplectic literature alongside modern categorical frameworks. Given the high cross-framework traction and successful achievement of its technical aims, the paper is suitable for inclusion as a preprint`,
ai_collaboration: `
This paper was developed through an iterative process involving an AI language model.
The AI contributed to structuring arguments, testing formulations, and refining exposition.
Final responsibility for content and claims remains human.
        `
    }, 
    /* Esempio di come aggiungere il prossimo:
    {
        title: "Titolo del prossimo saggio",
        author: "Nome Autore",
        ai_model: "GPT-5 / Gemini 2.0",
        date: "January 2026",
        pages: "15",
        pdf_file: "secondo_paper.pdf",
        readme_url: "https://whatever.org"
        abstract: "Qui scriverai l'abstract del secondo saggio..."
    }, 
    */
];
