/**
 * REPOSITORY DEI PAPER
 * Per aggiungere un paper: copia un blocco tra parentesi graffe e compilalo.
 */
const PAPERS_DATA = [
    {
        title: "The Invisible Pillar: On the Genesis and Concealment of Dualism from the Pre-Socratics to the Moderns",
        author: "Franco Cazzaniga",
        ai_model: "Claude Opus 4.5 (Anthropic)",
        date: "December 2025",
        pages: "20",
        pdf_file: "The Invisible Pillar.pdf",
        readme_url: "https://github.com/francocz/ai-theoretical.org",
        abstract: `This paper traces the genealogy of the dualism between intelligible and sensible, between \emph{logos} and matter, from its pre-Socratic background through its Platonic inauguration to its modern transformations. The central thesis is that Plato introduced a structural division that subsequent philosophy inherited, criticized superficially, re-articulated, but rarely questioned as a framework. The paper examines how this dualism was first epistemic and social (Plato's distinction between philosophical knowledge and common experience), then cosmological (the scientific revolution's separation between the mathematically describable real and the qualitatively perceived apparent), and finally metaphysical (Descartes' res cogitans and res extensa). The natural philosophers of the sixteenth and seventeenth centuries---Copernicus, Kepler, Galileo, Newton---are treated here as what they were: philosophers investigating nature, whose work deepened and transformed the Platonic distance between the true and the accessible. The aim is not to refute dualism but to make it visible as a historical structure, a framework that has become so assimilated as to be invisible.`
        ,
        ai_assessment: `
(A) STRUCTURED SUMMARY
Category: Expository / theoretical essay
Aims: Synthetic and critical reconstruction of the Platonic dualist framework.
Correctness: No errors identified.
Coherence: Adequate.
Consistency: Consistent.
Novelty: Reformulative.
Bibliography: Adequate.
Effectiveness: Achieves aims.
Cross-framework traction: High.
Editorial outcome: Suitable for inclusion as a preprint.

(B) EXTENDED ASSESSMENT The paper executes a synthetic analysis of the "intelligible-sensible" dualism, identified as an "invisible pillar" in Western thought. It identifies the Platonic inauguration of this structure and its subsequent re-articulations in hylomorphism, Neoplatonism, and medieval theology. A significant portion of the essay treats natural philosophers of the scientific revolution, such as Galileo and Newton, as philosophical investigators who transitioned the dualism from an epistemic-social distinction to a cosmological-mathematical one. The author argues that Cartesian dualism represents an interiorization of this framework rather than a radical departure. The bibliography is adequate, referencing standard scholarship to anchor these genealogical claims. The text achieves its aim of demonstrating how the framework remains embedded in modern inquiries by limiting reality to what is captureable by logos. Therefore, the essay is suitable for inclusion as a preprint.`,

        ai_collaboration: `
This paper was developed through an iterative process involving an AI language model.
The AI contributed to structuring arguments, testing formulations, and refining exposition.
Final responsibility for content and claims remains human.
        `
    },
{
        title: "The Invisible Wealth",
        author: "Franco Cazzaniga",
        ai_model: "Claude Opus 4.5 (Anthropic) / GPT-5 / Gemini 2.0",
        date: "December 2025",
        pages: "53",
        file: "The Invisible Wealth.pdf",
        readme_url: "https://github.com/francocz/ai-theoretical.org",
        abstract: `The dominant narrative of contemporary political economy holds that advanced economies have experienced decades of stagnating real wages and rising inequality, with the gains from technological progress accruing to a shrinking elite. This paper argues that this narrative rests on a statistical measurement illusion. Conventional national-accounts and consumer-price methodologies — designed for a mid-twentieth-century economy of standardized physical goods — systematically fail to capturethe value generated by quality improvements, dematerialization, and the creation ofentirely new goods and services.
We develop an attribute-based framework that reconceptualizes economic output as a flow of services from evolving bundles of characteristics rather than as quantities of nominally identical goods. Applying this framework to housing, durables, digital goods, and healthcare, we show that real living standards have improved far more rapidly than official statistics suggest. The consumer surplus from new and improved goods is economically equivalent to an expansion of real consumption possibilities: a worker with access to free navigation, global communication, and unlimited information commands a greater set of feasible choices than one without, even if their nominal incomes are identical.
The paper challenges the inevitability of Baumol’s Cost Disease through a comparative analysis of two U.S. hospitals and a high-volume Indian tertiary-care center, showing that when institutional frictions are minimal, medical technology achievessubstantially lower costs than prevailing U.S. benchmarks. The findings suggest that much of the “inequality crisis” reflects a crisis of measurement rather than a decline in real living standards.`,
        ai_assessment: `(A) STRUCTURED SUMMARY
Category: Research preprint
Aims: To provide a synthetic and critical re-conceptualization of real income, productivity, and inequality by arguing that standard economic statistics systematically understate welfare growth due to quality change, dematerialization, and risk reduction.
Correctness: No errors identified.
Coherence: Adequate.
Consistency: Consistent.
Novelty: Original.
Bibliography: Adequate.
Effectiveness: Achieves aims.
Cross-framework traction: High.
Editorial outcome: Suitable for inclusion as a preprint.

(B) EXTENDED ASSESSMENT
The manuscript presents a tightly argued theoretical framework that challenges dominant interpretations of wage stagnation and inequality by locating the problem in measurement rather than in underlying welfare dynamics. The argument is internally coherent and consistently developed from conceptual foundations through formal modeling and sectoral illustration. The attribute-based framework is clearly defined, mathematically explicit, and systematically applied across multiple domains, avoiding ad hoc reasoning. Claims are anchored in established literatures on hedonic pricing, consumer surplus, and risk valuation, and the bibliography is commensurate with the scope and ambition of the work 
No formal or conceptual errors undermine the analysis. While the conclusions are strong, they follow logically from the stated premises and from the distinction between measured output, welfare, and power. The paper demonstrates substantial cross-framework traction by engaging macroeconomics, welfare theory, inequality research, and institutional analysis without becoming cognitively closed. Its contribution is not incremental but reconstructive, offering a unifying lens rather than a narrow extension of existing models. The work achieves its stated aims at the level appropriate for a high-level theoretical preprint and meets the platform’s standards for inclusion.`,
        ai_collaboration: `
This paper was developed through an iterative process involving an AI language model.
The AI contributed to structuring arguments, testing formulations, and refining exposition.
Final responsibility for content and claims remains human.
        `
    }, 
    /* Esempio di come aggiungere il prossimo:
    {
        title: "Titolo del prossimo saggio",
        author: "Nome Autore",
        ai_model: "GPT-5 / Gemini 2.0",
        date: "January 2026",
        pages: "15",
        file: "secondo_paper.pdf",
        readme_url: "https://whatever.org"
        abstract: "Qui scriverai l'abstract del secondo saggio..."
    }, 
    */
];
